//! @generated by `cargo xtask gen-contracts` — DO NOT EDIT BY HAND.
//!
//! Source of truth: the byte-pinned mirrors under `docs/architecture/abi/`
//! (upstream revision in that directory's README). Regenerate with
//! `cargo xtask gen-contracts` after a mirror update; commit together.

use crate::generated::ArchitectureErrorCode;
use crate::layout::{AbiStructGolden, AbiTypeGolden};

pub(crate) const ABI_POINTER_BYTES: u32 = 8;
pub(crate) const ABI_MAX_ALIGNMENT: u32 = 8;

#[rustfmt::skip]
pub(crate) const ABI_TYPE_GOLDEN: &[AbiTypeGolden] = &[
    AbiTypeGolden { name: "lumio_status_t", size: 4, align: 4 },
    AbiTypeGolden { name: "lumio_handle_t", size: 16, align: 8 },
    AbiTypeGolden { name: "lumio_buffer_t", size: 24, align: 8 },
];

#[rustfmt::skip]
pub(crate) const ABI_STRUCT_GOLDEN: &[AbiStructGolden] = &[
    AbiStructGolden { name: "lumio_root_api", declared_size: 64, minimum_size: 32, members: &[
        ("abi_version", 0),
        ("struct_size", 4),
        ("capability_bits", 8),
        ("lumio_core_api", 16),
        ("lumio_voxel_api", 24),
    ] },
    AbiStructGolden { name: "lumio_core_api", declared_size: 48, minimum_size: 48, members: &[
        ("version", 0),
        ("struct_size", 4),
        ("reserved0", 8),
        ("lumio_core_init", 16),
        ("lumio_core_shutdown", 24),
        ("lumio_core_last_error_detail", 32),
    ] },
    AbiStructGolden { name: "lumio_voxel_api", declared_size: 32, minimum_size: 32, members: &[
        ("version", 0),
        ("struct_size", 4),
        ("reserved0", 8),
        ("lumio_voxel_world_create", 16),
        ("lumio_voxel_world_destroy", 24),
    ] },
];

#[rustfmt::skip]
pub(crate) const ABI_TABLE_VERSIONS: &[(&str, u32)] = &[
    ("lumio_core_api", 1),
    ("lumio_voxel_api", 1),
];

#[rustfmt::skip]
pub(crate) const ERROR_CODES: &[ArchitectureErrorCode] = &[
    ArchitectureErrorCode::new("RevisionConflict", 1001),
    ArchitectureErrorCode::new("MaintenanceKick", 1002),
    ArchitectureErrorCode::new("ReleaseMismatch", 1003),
    ArchitectureErrorCode::new("NativeAbiMismatch", 1004),
    ArchitectureErrorCode::new("StaleEpoch", 1005),
    ArchitectureErrorCode::new("FencingTokenStale", 1006),
    ArchitectureErrorCode::new("ManifestMalformed", 1007),
    ArchitectureErrorCode::new("ManifestUnsupportedVersion", 1008),
    ArchitectureErrorCode::new("ManifestDigestMismatch", 1009),
    ArchitectureErrorCode::new("ArtifactMissing", 1010),
    ArchitectureErrorCode::new("ArtifactDigestMismatch", 1011),
    ArchitectureErrorCode::new("SignatureMissing", 1012),
    ArchitectureErrorCode::new("SignatureInvalid", 1013),
    ArchitectureErrorCode::new("TrustRootUnknown", 1014),
    ArchitectureErrorCode::new("TrustPolicyRejected", 1015),
    ArchitectureErrorCode::new("KeyRevoked", 1016),
    ArchitectureErrorCode::new("EvidenceMissing", 1017),
    ArchitectureErrorCode::new("EvidenceDigestMismatch", 1018),
    ArchitectureErrorCode::new("TargetProfileMismatch", 1019),
    ArchitectureErrorCode::new("CapabilityMissing", 1020),
    ArchitectureErrorCode::new("SymbolMissing", 1021),
    ArchitectureErrorCode::new("SymbolCollision", 1022),
    ArchitectureErrorCode::new("PackageIdentityConflict", 1023),
    ArchitectureErrorCode::new("WorkerPoolDuplicate", 1024),
    ArchitectureErrorCode::new("LoaderTimeout", 1025),
    ArchitectureErrorCode::new("LoaderCancelled", 1026),
    ArchitectureErrorCode::new("LoaderOutOfMemory", 1027),
    ArchitectureErrorCode::new("PartialLoadRolledBack", 1028),
    ArchitectureErrorCode::new("InvalidHandle", 1029),
    ArchitectureErrorCode::new("HandleDoubleRelease", 1030),
    ArchitectureErrorCode::new("MessagePermissionDenied", 1031),
    ArchitectureErrorCode::new("StaleConnectionGeneration", 1032),
    ArchitectureErrorCode::new("ChunkUnavailable", 1033),
    ArchitectureErrorCode::new("TargetRevisionUnavailable", 1034),
    ArchitectureErrorCode::new("BudgetExceeded", 1035),
    ArchitectureErrorCode::new("QueueFull", 1036),
    ArchitectureErrorCode::new("CoordinateOutOfBounds", 1037),
    ArchitectureErrorCode::new("DirtyChunkNotDurable", 1038),
    ArchitectureErrorCode::new("SnapshotBaseMismatch", 1039),
    ArchitectureErrorCode::new("SessionMismatch", 1040),
    ArchitectureErrorCode::new("RoleMismatch", 1041),
    ArchitectureErrorCode::new("ClaimNotGranted", 1042),
    ArchitectureErrorCode::new("SessionAntiReplay", 1043),
    ArchitectureErrorCode::new("InvalidArgument", 1044),
    ArchitectureErrorCode::new("WrongContext", 1045),
    ArchitectureErrorCode::new("BufferTooSmall", 1046),
    ArchitectureErrorCode::new("CapacityExceeded", 1047),
    ArchitectureErrorCode::new("Cancelled", 1048),
    ArchitectureErrorCode::new("TimedOut", 1049),
    ArchitectureErrorCode::new("ContextClosing", 1050),
    ArchitectureErrorCode::new("ContextDestroyed", 1051),
    ArchitectureErrorCode::new("PanicBoundary", 1052),
    ArchitectureErrorCode::new("InternalInvariant", 1053),
];
