//! @generated by `cargo xtask gen-contracts` — DO NOT EDIT BY HAND.
//!
//! Source of truth: the byte-pinned mirrors under `docs/architecture/abi/`
//! (upstream revision in that directory's README). Regenerate with
//! `cargo xtask gen-contracts` after a mirror update; commit together.

use crate::layout::{AbiStructGolden, AbiTypeGolden};

pub(crate) const ABI_POINTER_BYTES: u32 = 8;
pub(crate) const ABI_MAX_ALIGNMENT: u32 = 8;

#[rustfmt::skip]
pub(crate) const ABI_TYPE_GOLDEN: &[AbiTypeGolden] = &[
    AbiTypeGolden { name: "lumio_status_t", size: 4, align: 4 },
    AbiTypeGolden { name: "lumio_handle_t", size: 16, align: 8 },
    AbiTypeGolden { name: "lumio_buffer_t", size: 24, align: 8 },
];

#[rustfmt::skip]
pub(crate) const ABI_STRUCT_GOLDEN: &[AbiStructGolden] = &[
    AbiStructGolden { name: "lumio_root_api", declared_size: 64, minimum_size: 32, members: &[
        ("abi_version", 0),
        ("struct_size", 4),
        ("capability_bits", 8),
        ("lumio_core_api", 16),
        ("lumio_voxel_api", 24),
    ] },
    AbiStructGolden { name: "lumio_core_api", declared_size: 48, minimum_size: 48, members: &[
        ("version", 0),
        ("struct_size", 4),
        ("reserved0", 8),
        ("lumio_core_init", 16),
        ("lumio_core_shutdown", 24),
        ("lumio_core_last_error_detail", 32),
    ] },
    AbiStructGolden { name: "lumio_voxel_api", declared_size: 32, minimum_size: 32, members: &[
        ("version", 0),
        ("struct_size", 4),
        ("reserved0", 8),
        ("lumio_voxel_world_create", 16),
        ("lumio_voxel_world_destroy", 24),
    ] },
];
